site_name: maPlan
site_url: https://zbmed-semtec.github.io/maPlan
nav:
    - 'index.md'
    - Tutorials:
      - 'Tutorials/ModelCards.md'
      - 'Tutorials/FAIR4ML.md'
      - 'Tutorials/MLentory.md'
    - 'about.md'
      
    
theme:
  name: material
  logo: maPlan_plain_logo.png

  language: en
  palette:
    - scheme: default
      primary: blue grey
      accent: amber 

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zbmed-semtec/maPlan
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search

copyright: >
  '<hr/><table align="center" style="width:100%"><tr>
  <td><a href="https://www.zbmed.de/en/legal-notice" target="_blank">Legal notice</a></td>
  <td><a href="https://www.zbmed.de/en/disclaimer" target="_blank">Disclaimer</a></td>
  <td><a href="https://www.zbmed.de/en/privacy-policy" target="_blank">Privacy policy</a></td>
  </tr></table>'


  

