site_name: maPlan - a project by ZB MED
site_url: https://zbmed-semtec.github.io/maPlan
nav:
    - 'index.md'
    - Tutorials:
      - 'Tutorials/ModelCards.md'
      - 'Tutorials/FAIR4ML.md'
      - 'Tutorials/MLentory.md'
    - 'about.md'
      
    
theme:
  name: material
  logo: maPlan_plain_logo.png

  language: en
  palette:
    - scheme: default
      primary: blue grey
      accent: amber 

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zbmed-semtec/maPlan
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search

copyright: >
  <div style="font-size:large; color:orange">
  <a href="https://www.zbmed.de/en/" target="_blank">ZB MED</a> | 
  <a href="https://www.zbmed.de/en/legal-notice" target="_blank">Legal notice</a> | 
  <a href="https://www.zbmed.de/en/disclaimer" target="_blank">Disclaimer</a> | 
  <a href="https://www.zbmed.de/en/privacy-policy" target="_blank">Privacy policy</a>
  </div>

  

